CMTPATH=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface
CMT_tag=$(tag)
CMTROOT=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/CMT/v1r26
CMT_root=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/CMT/v1r26
CMTVERSION=v1r26
CMT_offset=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/InstallArea/${CMTCONFIG}/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/InstallArea/${CMTCONFIG}/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/CMT/v1r26/${CMTBIN}:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/MPICH/3.2.1/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/podio/master/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/python-yaml/5.1.2/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/libyaml/0.2.2/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/mysql-connector-cpp/1.1.8/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/mysql-connector-c/6.1.9/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/libmore/0.8.3/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Geant4/10.05.p01/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/HepMC/2.06.09/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/ROOT/6.18.00/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/xrootd/4.10.0/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/CLHEP/2.4.1.0/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/tbb/2019_U8/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/sqlite3/3.29.0/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/fftw3/3.3.8/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/gsl/2.5/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Xercesc/3.2.2/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Cmake/3.15.2/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Boost/1.72.0/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Python/2.7.15/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/gcc/8.3.0/bin:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/binutils/2.28/bin:/afs/ihep.ac.cn/users/y/yiph/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/bin:/usr/lib64/qt-3.3/bin:/usr/bin:/usr/externals/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/java/latest/bin:/opt/puppetlabs/bin:/usr/local/cuda/bin
CLASSPATH=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/CMT/v1r26/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags=-std=c++11 -fPIC -pipe -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp --log=./install.history 
uninstall_command=python $(SniperPolicy_root)/cmt/fragments/install.py -u --log=./install.history 
cmt_installarea_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl75-gcc830
MFSSvc_tag=$(tag)
MFSSVCROOT=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/CommonSvc/MFSSvc
MFSSvc_root=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/CommonSvc/MFSSvc
MFSSVCVERSION=v0
MFSSvc_cmtpath=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline
MFSSvc_offset=CommonSvc
MFSSvc_project=offline
SniperKernel_tag=$(tag)
SNIPERKERNELROOT=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/SniperKernel
SniperKernel_root=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/SniperKernel
SNIPERKERNELVERSION=v2
SniperKernel_cmtpath=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper
SniperKernel_project=sniper
SniperPolicy_tag=$(tag)
SNIPERPOLICYROOT=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/SniperPolicy
SniperPolicy_root=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/SniperPolicy
SNIPERPOLICYVERSION=v0
SniperPolicy_cmtpath=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper
SniperPolicy_project=sniper
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined 
application_linkopts=-Wl,--export-dynamic 
BINDIR=$(tag)
remove_command=$(cmt_uninstallarea_command)
Boost_tag=$(tag)
BOOSTROOT=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface/Externals/Boost
Boost_root=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface/Externals/Boost
BOOSTVERSION=v0
Boost_cmtpath=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface
Boost_offset=Externals
Boost_project=ExternalInterface
Python_tag=$(tag)
PYTHONROOT=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface/Externals/Python
Python_root=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface/Externals/Python
PYTHONVERSION=v0
Python_cmtpath=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface
Python_offset=Externals
Python_project=ExternalInterface
Python_linkopts= `pkg-config --libs python` 
Python_cppflags= `pkg-config --cflags python` 
Boost_home=${JUNO_EXTLIB_Boost_HOME}
Boost_pysuffix=${BOOST_PYTHON_SUFFIX}
Boost_linkopts= -L$(Boost_home)/lib  -lboost_python$(Boost_pysuffix)  -lboost_filesystem  -lboost_thread  -lboost_mpi  -lboost_serialization  -lboost_system  -lboost_chrono  -lboost_date_time  -lboost_atomic  -lpthread 
includes= $(ppcmd)"$(MFSSvc_root)"  $(ppcmd)"$(srcdir)" $(ppcmd)"/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/InstallArea/include" $(ppcmd)"/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/InstallArea/include" $(use_includes)
PYTHONPATH=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/InstallArea/python:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/InstallArea/python:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/InstallArea/amd64_linux26/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/InstallArea/amd64_linux26/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/python-yaml/5.1.2/lib/python2.7/site-packages:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/ROOT/6.18.00/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/xrootd/4.10.0/lib64/python2.7/site-packages:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Python/2.7.15/lib/./python2.7/lib-dynload:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Python/2.7.15/lib/python2.7/site-packages:/usr/lib64/python
SniperKernel_linkopts= -lSniperKernel  -lSniperPython 
SniperKernel_stamps=${SNIPERKERNELROOT}/${BINDIR}/SniperPython.stamp 
SniperKernel_linker_library=SniperPython
SniperPython_dependencies=SniperKernel
SniperPython_shlibflags= -lSniperKernel 
MPI_tag=$(tag)
MPIROOT=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface/Externals/MPI
MPI_root=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface/Externals/MPI
MPIVERSION=v0
MPI_cmtpath=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface
MPI_offset=Externals
MPI_project=ExternalInterface
MPI_home=${JUNO_EXTLIB_MPI_HOME}
MPI_linkopts= -L$(MPI_home)/lib  -lmpi  -lmpicxx 
MFSSvc_linkopts= -lMFSSvc 
MFSSvc_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(MFSSvc_use_linkopts)
MFSSvc_use_linkopts=    $(SniperKernel_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(MPI_linkopts) 
MFSSvc_stamps=${MFSSVCROOT}/${BINDIR}/MFSSvc.stamp 
MFSSvc_linker_library=MFSSvc
tag=amd64_linux26
package=MFSSvc
version=v0
PACKAGE_ROOT=$(MFSSVCROOT)
srcdir=../src
bin=../$(MFSSvc_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/CommonSvc/MFSSvc/amd64_linux26/
project=offline
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(sniper_installarea_prefix)/$(CMTCONFIG)/lib $(sniper_installarea_prefix)/share/lib $(sniper_installarea_prefix)/share/bin $(offline_installarea_prefix)/$(CMTCONFIG)/lib $(offline_installarea_prefix)/share/lib $(offline_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(MFSSvc_linkopts)  $(SniperKernel_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(MPI_linkopts) 
ExternalInterface_installarea_prefix=$(cmt_installarea_prefix)
ExternalInterface_installarea_prefix_remove=$(ExternalInterface_installarea_prefix)
LD_LIBRARY_PATH=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/InstallArea/${CMTCONFIG}/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/InstallArea/${CMTCONFIG}/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/MPICH/3.2.1/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/podio/master/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/python-yaml/5.1.2/lib/python2.7/site-packages:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/python-yaml/5.1.2/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/libyaml/0.2.2/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/mysql-connector-cpp/1.1.8/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/mysql-connector-c/6.1.9/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/libmore/0.8.3/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Geant4/10.05.p01/lib64:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/HepMC/2.06.09/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/ROOT/6.18.00/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/xrootd/4.10.0/lib64/python2.7/site-packages:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/xrootd/4.10.0/lib64:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/CLHEP/2.4.1.0/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/tbb/2019_U8/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/sqlite3/3.29.0/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/fftw3/3.3.8/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/gsl/2.5/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Xercesc/3.2.2/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Boost/1.72.0/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Python/2.7.15/lib/python2.7/site-packages:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Python/2.7.15/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/gcc/8.3.0/lib64:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/gcc/8.3.0/lib:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/binutils/2.28/lib64:/hpcfs/juno/junogpu/yiph/Muon/software/sl7/binutils/2.28/lib:/usr/lib64/classads:/usr/lib64:/usr/lib:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
sniper_installarea_prefix=$(cmt_installarea_prefix)
sniper_installarea_prefix_remove=$(sniper_installarea_prefix)
offline_installarea_prefix=$(cmt_installarea_prefix)
offline_installarea_prefix_remove=$(offline_installarea_prefix)
cmt_installarea_linkopts= -L/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/$(offline_installarea_prefix)/$(CMTCONFIG)/lib  -L/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/$(sniper_installarea_prefix)/$(CMTCONFIG)/lib 
ExternalInterface_home=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalInterface
sniper_home=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper
offline_home=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline
offline_install_include= /hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/$(offline_installarea_prefix)/include 
sniper_install_include= /hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/$(sniper_installarea_prefix)/include 
sniper_python_path=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/$(sniper_installarea_prefix)/$(tag)/lib
offline_python_path=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/$(offline_installarea_prefix)/$(tag)/lib
sniper_install_python=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/sniper/$(sniper_installarea_prefix)/python
offline_install_python=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/$(offline_installarea_prefix)/python
CMTINSTALLAREA=/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/offline/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(SniperKernel_root)/cmt/requirements $(SniperPolicy_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(MPI_root)/cmt/requirements 
use_includes= $(ppcmd)"$(SniperKernel_root)/src" $(ppcmd)"$(SniperPolicy_root)/src" $(ppcmd)"/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/Boost/1.72.0/include" $(ppcmd)"$(Python_root)/src" $(ppcmd)"/hpcfs/juno/junogpu/yiph/Muon/software/sl7/J19v1r1-branch/ExternalLibs/MPICH/3.2.1/include" 
use_fincludes= $(use_includes)
use_stamps=  $(MFSSvc_stamps)  $(SniperKernel_stamps)  $(SniperPolicy_stamps)  $(Boost_stamps)  $(Python_stamps)  $(MPI_stamps) 
use_cflags=  $(MFSSvc_cflags)  $(SniperKernel_cflags)  $(SniperPolicy_cflags)  $(Boost_cflags)  $(Python_cflags)  $(MPI_cflags) 
use_pp_cflags=  $(MFSSvc_pp_cflags)  $(SniperKernel_pp_cflags)  $(SniperPolicy_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags)  $(MPI_pp_cflags) 
use_cppflags=  $(MFSSvc_cppflags)  $(SniperKernel_cppflags)  $(SniperPolicy_cppflags)  $(Boost_cppflags)  $(Python_cppflags)  $(MPI_cppflags) 
use_pp_cppflags=  $(MFSSvc_pp_cppflags)  $(SniperKernel_pp_cppflags)  $(SniperPolicy_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags)  $(MPI_pp_cppflags) 
use_fflags=  $(MFSSvc_fflags)  $(SniperKernel_fflags)  $(SniperPolicy_fflags)  $(Boost_fflags)  $(Python_fflags)  $(MPI_fflags) 
use_pp_fflags=  $(MFSSvc_pp_fflags)  $(SniperKernel_pp_fflags)  $(SniperPolicy_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags)  $(MPI_pp_fflags) 
use_libraries= $(SniperKernel_libraries)  $(SniperPolicy_libraries)  $(Boost_libraries)  $(Python_libraries)  $(MPI_libraries) 
fincludes= $(includes)
install_more_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MFSSvc_python_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
MFSSvc_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= install_more_includes MFSSvc_python MFSSvc 
all_constituents= $(constituents)
constituentsclean= MFSSvcclean MFSSvc_pythonclean install_more_includesclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
MFSSvcprototype_dependencies= $(MFSSvccompile_dependencies)
